TRUNCATE TABLE role RESTART IDENTITY CASCADE;
INSERT INTO role (name) VALUES ('ADMIN') ON CONFLICT DO NOTHING;
INSERT INTO role (name) VALUES ('CLIENT') ON CONFLICT DO NOTHING;
INSERT INTO role (name) VALUES ('DRIVER') ON CONFLICT DO NOTHING;
